dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  include:
    - php: 7.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/ --exclude=Generic.Files.LineLength
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  email: false
